/*******************************************************************************
 * Copyright (c) 2011 Tasktop Technologies.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     Tasktop Technologies - initial API and implementation
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider */

#ifndef _Included_org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider
#define _Included_org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider
 * Method:    performNativeSearch
 * Signature: (Lorg/eclipse/mylyn/internal/sandbox/search/ui/SearchCriteria;Lorg/eclipse/mylyn/internal/sandbox/search/ui/SearchCallback;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider_performNativeSearch
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider_MyCallback */

#ifndef _Included_org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider_MyCallback
#define _Included_org_eclipse_mylyn_internal_sandbox_search_ui_Windows7SearchProvider_MyCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
